// <auto-generated />
using System;
using MTCrepository.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MTC_WebServerCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210817124459_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MTCmodel.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("nvarchar(56)");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumberAdditional")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("MTCmodel.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemovable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            ConcurrencyStamp = "79438ccc-b82d-4712-9448-4bed72d0e1ef",
                            IsRemovable = false,
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "c6aaef1a-8312-4185-8b51-1e3a09421ff7",
                            ConcurrencyStamp = "ce6f90a3-eb6d-4fe6-885a-641e2be3a398",
                            IsRemovable = false,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "7e19e371-55db-4c16-b9c0-4103de5b39fd",
                            ConcurrencyStamp = "884035dc-23d6-4870-8cff-fb185fe6ef12",
                            IsRemovable = false,
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = "1dde702e-2587-41bd-bec5-0f4cc5d05498",
                            ConcurrencyStamp = "fdc3760e-eab3-4825-8dbd-01dc403fdcd1",
                            IsRemovable = false,
                            Name = "Transporter",
                            NormalizedName = "TRANSPORTER"
                        },
                        new
                        {
                            Id = "277f86fd-db6a-449a-a7de-25917a177a61",
                            ConcurrencyStamp = "ca01224a-283c-4048-b1f9-e3d6e27cd3e3",
                            IsRemovable = false,
                            Name = "Supplier",
                            NormalizedName = "SUPPLIER"
                        });
                });

            modelBuilder.Entity("MTCmodel.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemovable")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb3cd166-6f24-4071-8954-682ef98b2066",
                            Email = "super@user.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            IsRemovable = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPER@USER.COM",
                            NormalizedUserName = "SUPER@USER.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMHMkHnLvavXi/fIfe4ciSXJ8Yj0TKP/HdOYa0Zrj/5OSdkbW91WjPP5N303DiCFpg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d1da164e-8a0d-433d-91d6-f097690fcde1",
                            TwoFactorEnabled = false,
                            UserName = "super@user.com"
                        },
                        new
                        {
                            Id = "e08d7ef7-2615-4385-844f-81834bb6e776",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f853e240-d182-454f-9751-4f217b9a8ef1",
                            Email = "client@mtc.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            IsRemovable = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT@MTC.COM",
                            NormalizedUserName = "CLIENT@MTC.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELhOQ0Jko7SyTnTPRxqC4y8V8KtHUn5Jh8hEg9wXYCZNzdhg+7w3PxpuQWYcj6tkyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "baaa9dcf-26fd-4d62-9bfb-81a5bb4703b4",
                            TwoFactorEnabled = false,
                            UserName = "client@mtc.com"
                        },
                        new
                        {
                            Id = "a0392e57-a71c-4314-b87c-ba8dc7628fcc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9d0c8408-4320-4f6f-9c59-45380c6d2fa7",
                            Email = "transporter@mtc.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            IsRemovable = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "TRANSPORTER@MTC.COM",
                            NormalizedUserName = "TRANSPORTER@MTC.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOb/8QhMBueLQRXy1QG1mEwBPPbUeDX0Rfub2YKmSMOC9w4GpBDO1/YIZdnOpQDmPg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c3cf937c-c6ea-49fc-a7ae-3e25656af579",
                            TwoFactorEnabled = false,
                            UserName = "transporter@mtc.com"
                        },
                        new
                        {
                            Id = "f0cd17fb-639c-4bd4-aa51-cb64259d9743",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d9a17586-dd2e-42a9-9fca-c320c1a2a6a4",
                            Email = "supplier@mtc.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            IsRemovable = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPPLIER@MTC.COM",
                            NormalizedUserName = "SUPPLIER@MTC.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENhZE4dQ151J5QVShmiFbyokd8EA1ls9nR5IR5K8OObM4nsXm0bNyAvCwJzdPkWYlQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb0a0f40-16d1-40ee-94a3-41e3288096b0",
                            TwoFactorEnabled = false,
                            UserName = "supplier@mtc.com"
                        },
                        new
                        {
                            Id = "c6bbcf91-ab26-4bf1-a8ac-6251444d1464",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "475ee17e-4fd2-4f66-a7fa-972723bafd62",
                            Email = "UserAdmin@mtc.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            IsRemovable = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USERADMIN@MTC.COM",
                            NormalizedUserName = "USERADMIN@MTC.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIEeZXew7++zlADFQSZEd6z0ed39H9u5u8jwJ0Q8QSuVDlB58XBRxS/kafF92Fowpg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "577f2c5f-5d8b-44eb-93c8-b6d7e28a5e1d",
                            TwoFactorEnabled = false,
                            UserName = "UserAdmin@mtc.com"
                        });
                });

            modelBuilder.Entity("MTCmodel.Bonus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<int>("OrderOUTId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Code");

                    b.HasIndex("ClientID");

                    b.HasIndex("OrderOUTId");

                    b.ToTable("Bonusses");
                });

            modelBuilder.Entity("MTCmodel.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("DiscountPercentage")
                        .HasColumnType("float");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NameAdditional")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            DiscountPercentage = 0.0,
                            FirstName = "Super",
                            LastName = "User"
                        },
                        new
                        {
                            Id = "e08d7ef7-2615-4385-844f-81834bb6e776",
                            DiscountPercentage = 0.0,
                            FirstName = "testClientvoornaam",
                            LastName = "testclientAchternaam",
                            NameAdditional = "tst"
                        });
                });

            modelBuilder.Entity("MTCmodel.OrderIN", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupplierID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("SupplierID");

                    b.ToTable("OrderINs");
                });

            modelBuilder.Entity("MTCmodel.OrderLineIN", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderINID")
                        .HasColumnType("int");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("OrderINID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderLineINs");
                });

            modelBuilder.Entity("MTCmodel.OrderLineOUT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderOUTId")
                        .HasColumnType("int");

                    b.Property<string>("ProductEAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransporterId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderOUTId");

                    b.HasIndex("ProductEAN");

                    b.HasIndex("TransporterId");

                    b.ToTable("OrderLineOUTs");
                });

            modelBuilder.Entity("MTCmodel.OrderOUT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountClientPercentage")
                        .HasColumnType("float");

                    b.Property<int>("HouseNumber")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("HouseNumberAdditional")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("OrderOUTs");
                });

            modelBuilder.Entity("MTCmodel.Product", b =>
                {
                    b.Property<string>("EAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("float");

                    b.Property<double>("BTWPercentage")
                        .HasColumnType("float");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<int>("CountInStock")
                        .HasColumnType("int");

                    b.Property<string>("ExtraInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxStock")
                        .HasColumnType("int");

                    b.Property<int>("MinStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("int");

                    b.Property<double>("RecommendedUnitPrice")
                        .HasColumnType("float");

                    b.Property<double?>("SolderPrice")
                        .HasColumnType("float");

                    b.HasKey("EAN");

                    b.HasIndex("CategorieId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MTCmodel.ProductCategorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentCategorieID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ParentCategorieID", "Name")
                        .IsUnique()
                        .HasFilter("[ParentCategorieID] IS NOT NULL");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("MTCmodel.ProductImage", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProductEAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ProductEAN");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("MTCmodel.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductEAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProductEAN");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("MTCmodel.ReturnedProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NewOrderLineOUTID")
                        .HasColumnType("int");

                    b.Property<int>("OrderLineOUTID")
                        .HasColumnType("int");

                    b.Property<bool>("Outlet")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClientId");

                    b.HasIndex("EAN");

                    b.ToTable("ReturnedProducts");
                });

            modelBuilder.Entity("MTCmodel.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BTW")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompanyNummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebSite")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            BTW = "BE0123456789",
                            CompanyNummer = "0123456789",
                            Name = "MTCSuperUserSupplier",
                            WebSite = "www.MTCtestsupplier.be"
                        },
                        new
                        {
                            Id = "f0cd17fb-639c-4bd4-aa51-cb64259d9743",
                            BTW = "22222222222222",
                            CompanyNummer = "22222222222",
                            Name = "TestSupplier",
                            WebSite = "www.MTCtestsupplier.be"
                        });
                });

            modelBuilder.Entity("MTCmodel.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestModel");
                });

            modelBuilder.Entity("MTCmodel.Transporter", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transporters");

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            Name = "MTCSuperUserTransporter"
                        },
                        new
                        {
                            Id = "a0392e57-a71c-4314-b87c-ba8dc7628fcc",
                            Name = "TestTransporter"
                        });
                });

            modelBuilder.Entity("MTCmodel.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TransporterID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TransporterID");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "c6aaef1a-8312-4185-8b51-1e3a09421ff7"
                        },
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "7e19e371-55db-4c16-b9c0-4103de5b39fd"
                        },
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "1dde702e-2587-41bd-bec5-0f4cc5d05498"
                        },
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "277f86fd-db6a-449a-a7de-25917a177a61"
                        },
                        new
                        {
                            UserId = "e08d7ef7-2615-4385-844f-81834bb6e776",
                            RoleId = "7e19e371-55db-4c16-b9c0-4103de5b39fd"
                        },
                        new
                        {
                            UserId = "a0392e57-a71c-4314-b87c-ba8dc7628fcc",
                            RoleId = "1dde702e-2587-41bd-bec5-0f4cc5d05498"
                        },
                        new
                        {
                            UserId = "f0cd17fb-639c-4bd4-aa51-cb64259d9743",
                            RoleId = "277f86fd-db6a-449a-a7de-25917a177a61"
                        },
                        new
                        {
                            UserId = "c6bbcf91-ab26-4bf1-a8ac-6251444d1464",
                            RoleId = "c6aaef1a-8312-4185-8b51-1e3a09421ff7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ProductSupplier", b =>
                {
                    b.Property<string>("ProductsEAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SuppliersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductsEAN", "SuppliersId");

                    b.HasIndex("SuppliersId");

                    b.ToTable("ProductSupplier");
                });

            modelBuilder.Entity("MTCmodel.Address", b =>
                {
                    b.HasOne("MTCmodel.ApplicationUser", "ApplicationUser")
                        .WithMany("Addresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MTCmodel.Bonus", b =>
                {
                    b.HasOne("MTCmodel.Client", "Client")
                        .WithMany("Bonuses")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MTCmodel.OrderOUT", "OrderOUT")
                        .WithMany("Bonusses")
                        .HasForeignKey("OrderOUTId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("OrderOUT");
                });

            modelBuilder.Entity("MTCmodel.Client", b =>
                {
                    b.HasOne("MTCmodel.ApplicationUser", "ApplicationUser")
                        .WithOne("Client")
                        .HasForeignKey("MTCmodel.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MTCmodel.OrderIN", b =>
                {
                    b.HasOne("MTCmodel.Supplier", "Supplier")
                        .WithMany("OrdersINs")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MTCmodel.OrderLineIN", b =>
                {
                    b.HasOne("MTCmodel.OrderIN", "OrderIN")
                        .WithMany("OrderLinesINs")
                        .HasForeignKey("OrderINID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MTCmodel.Product", "Product")
                        .WithMany("OrderLineINs")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OrderIN");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MTCmodel.OrderLineOUT", b =>
                {
                    b.HasOne("MTCmodel.OrderOUT", "OrderOUT")
                        .WithMany("OrderLineOUTs")
                        .HasForeignKey("OrderOUTId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MTCmodel.Product", "Product")
                        .WithMany("OrderLineOUTs")
                        .HasForeignKey("ProductEAN")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MTCmodel.Transporter", "Transporter")
                        .WithMany("orderLineOUTs")
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OrderOUT");

                    b.Navigation("Product");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("MTCmodel.OrderOUT", b =>
                {
                    b.HasOne("MTCmodel.Client", "Client")
                        .WithMany("OrderOUTs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MTCmodel.Product", b =>
                {
                    b.HasOne("MTCmodel.ProductCategorie", "Categorie")
                        .WithMany("Products")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("MTCmodel.ProductCategorie", b =>
                {
                    b.HasOne("MTCmodel.ProductCategorie", "ParentCategorie")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategorieID");

                    b.Navigation("ParentCategorie");
                });

            modelBuilder.Entity("MTCmodel.ProductImage", b =>
                {
                    b.HasOne("MTCmodel.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductEAN")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MTCmodel.ProductReview", b =>
                {
                    b.HasOne("MTCmodel.Client", "Client")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MTCmodel.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductEAN")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MTCmodel.ReturnedProduct", b =>
                {
                    b.HasOne("MTCmodel.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTCmodel.Product", "Product")
                        .WithMany("ReturnedProducts")
                        .HasForeignKey("EAN")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MTCmodel.Supplier", b =>
                {
                    b.HasOne("MTCmodel.ApplicationUser", "ApplicationUser")
                        .WithOne("Supplier")
                        .HasForeignKey("MTCmodel.Supplier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MTCmodel.Transporter", b =>
                {
                    b.HasOne("MTCmodel.ApplicationUser", "ApplicationUser")
                        .WithOne("Transporter")
                        .HasForeignKey("MTCmodel.Transporter", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MTCmodel.Zone", b =>
                {
                    b.HasOne("MTCmodel.Transporter", "Transporter")
                        .WithMany("Zones")
                        .HasForeignKey("TransporterID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("MTCmodel.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MTCmodel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MTCmodel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("MTCmodel.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTCmodel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MTCmodel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductSupplier", b =>
                {
                    b.HasOne("MTCmodel.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsEAN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTCmodel.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SuppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTCmodel.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Client");

                    b.Navigation("Supplier");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("MTCmodel.Client", b =>
                {
                    b.Navigation("Bonuses");

                    b.Navigation("OrderOUTs");

                    b.Navigation("ProductReviews");
                });

            modelBuilder.Entity("MTCmodel.OrderIN", b =>
                {
                    b.Navigation("OrderLinesINs");
                });

            modelBuilder.Entity("MTCmodel.OrderOUT", b =>
                {
                    b.Navigation("Bonusses");

                    b.Navigation("OrderLineOUTs");
                });

            modelBuilder.Entity("MTCmodel.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OrderLineINs");

                    b.Navigation("OrderLineOUTs");

                    b.Navigation("ProductReviews");

                    b.Navigation("ReturnedProducts");
                });

            modelBuilder.Entity("MTCmodel.ProductCategorie", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("MTCmodel.Supplier", b =>
                {
                    b.Navigation("OrdersINs");
                });

            modelBuilder.Entity("MTCmodel.Transporter", b =>
                {
                    b.Navigation("orderLineOUTs");

                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
